// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqZHK33qNytlMQBRR7f53KzwaRSEwt9ro',
    appId: '1:366294231901:web:6133c0aa3685bbd83656b4',
    messagingSenderId: '366294231901',
    projectId: 'ecommerece-b4fe8',
    authDomain: 'ecommerece-b4fe8.firebaseapp.com',
    storageBucket: 'ecommerece-b4fe8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Ldth7AtinyDI8aOn9A3Q1DV-rau5-24',
    appId: '1:366294231901:android:ec92e56f5ed9cb623656b4',
    messagingSenderId: '366294231901',
    projectId: 'ecommerece-b4fe8',
    storageBucket: 'ecommerece-b4fe8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcjQ37YRcfM5TJhzzhLIeo5Qvwz4pB59o',
    appId: '1:366294231901:ios:6142ec78da6631623656b4',
    messagingSenderId: '366294231901',
    projectId: 'ecommerece-b4fe8',
    storageBucket: 'ecommerece-b4fe8.appspot.com',
    androidClientId: '366294231901-1a0jleefumeckgna91e985jamuc1r18q.apps.googleusercontent.com',
    iosClientId: '366294231901-3ojsbukiekbs270a7ufkdspqf0eolfh0.apps.googleusercontent.com',
    iosBundleId: 'com.ackerman.lexisnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcjQ37YRcfM5TJhzzhLIeo5Qvwz4pB59o',
    appId: '1:366294231901:ios:da0f09e7f8d5266f3656b4',
    messagingSenderId: '366294231901',
    projectId: 'ecommerece-b4fe8',
    storageBucket: 'ecommerece-b4fe8.appspot.com',
    androidClientId: '366294231901-1a0jleefumeckgna91e985jamuc1r18q.apps.googleusercontent.com',
    iosClientId: '366294231901-hq5h1vp7s9bk8v3big9j63oqc3l5qt8k.apps.googleusercontent.com',
    iosBundleId: 'com.ackerman.lexisnap.RunnerTests',
  );
}
